name: Generate TGV result
run-name: ${{ github.actor }} is running TGV result generation job 🚀
on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  Download-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Download reports
        run: node ./download-reports-TJV.js
      - name: Generate result
        run: node ./generate-result-TJV.js
      - run: echo "CurrentDT=$(date +'%d/%m %H')" >> $GITHUB_ENV
      - name: Push reports & result to repository
        uses: EndBug/add-and-commit@v9
        with:
          add: boats-TJV.json tracks-TJV.json boats_result_TJV.json
          message: "Update ${{ env.CurrentDT }}h GMT"
